services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      QDRANT_URL_ENDPOINT: http://qdrant:6333
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: fastapi dev main.py --host 0.0.0.0 --port 8000
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # HTTP API
      - "6334:6334" # gRPC API
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  qdrant-data: